os: linux
dist: xenial
language: python
python:
  - "3.6"

git:
  quiet: true

before_install:
  - git clone https://github.com/clementviolet/barlock
  - chmod u+x barlock/bootstrap.sh

install:
  - ./barlock/bootstrap.sh

script:
  - python barlock/build.py

before_deploy:
   - yes | rm -r barlock/

deploy:
  provider: pages
  cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  on:
     all_branches: true
